---
language: "python"
python:
  - "3.10"

# Install python packages and other necessary setup tasks.
install:
  - "make setup"

# Execute linting unit tests before running the main programs.
# If any of these tasks fail, the entire build fails immediately.
before_script:
  - "make lint"
  - "make unit"

# Run the script four times, using three explicit verbosities and one
# default setting just to make sure it doesn't barf exceptions.
script:
  - "make run"
...
